name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e-android:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Run E2E tests
        run: npm e2e:android
        env:
          DETOX_CONFIGURATION: android.emu.debug

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            e2e/test-results/
            detox-artifacts/

  e2e-ios:
    runs-on: macos-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          xcodebuild -workspace ios/RecipeOCR.xcworkspace \
            -scheme RecipeOCR \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -derivedDataPath ios/build

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Run E2E tests
        run: npm e2e:ios
        env:
          DETOX_CONFIGURATION: ios.sim.debug

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results-ios
          path: |
            e2e/test-results/
            detox-artifacts/
